name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        dotnet-version: 7.x.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish --configuration Release
      
    - name: Test
      run: dotnet test
      
    - name: Generate release tag
      id: tag
      run: echo "::set-output name=release_tag::SoulWorker_PasswordExtractor_$(date +"%Y.%m.%d_%H-%M")"
      
    - name: Zip
      run: tar -cvf ${{ steps.tag.outputs.release_tag }}.zip -C SoulWorker.PasswordExtractor.Cli/bin/Release/net7.0/publish/ *
      
    - name: Release
      uses: softprops/action-gh-release@master
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: ${{ steps.tag.outputs.release_tag }}.zip
        
        
